config/routes.rb
Rails.application.routes.draw do
  #resources :appointments
  devise_for :patients
  get 'home/index'

  devise_for :doctors
  devise_scope :doctor do
    get "signup", to: "doctors/registrations#new"
    get "login", to: "doctors/sessions#new"
    post "login", to: "doctors/sessions#create"
    get "logout", to: "doctors/sessions#destroy"
    post "signup", to: "doctors/registrations#create"
  end

  resources :appointments do
    get "update_status/:status", to: "appointments#update_status"
    get "send_prescription", to: "appointments#send_prescription"
    post "save_prescription", to: "appointments#save_prescription", on: :collection
  end

  root :to => "home#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end
  

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord
	belongs_to :doctor
	belongs_to :patient
	has_many :notes
end

app/models/doctor.rb
class Doctor < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :appointments

  def full_name
  	[first_name, last_name].join(" ")
  end
end

app/models/note.rb
class Note < ApplicationRecord
	belongs_to :appointment
	belongs_to :patient
	belongs_to :doctor
end

app/models/patient.rb
class Patient < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def full_name
  	[first_name, last_name].join(" ")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	#before_action :authenticate_doctor! 
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :set_appointment, only: [:show, :edit, :update, :destroy, :send_prescription]

  # GET /appointments
  # GET /appointments.json
  def index
    if params[:type]
      @appointments = current_doctor.appointments.where('start_time BETWEEN ? AND ?', DateTime.now.beginning_of_day, DateTime.now.end_of_day)
    else
      @appointments = current_doctor.appointments
    end
  end

  # GET /appointments/1
  # GET /appointments/1.json
  def show
  end

  # GET /appointments/new
  def new
    @doctor = Doctor.find(params[:id])
    @appointment = Appointment.new
  end

  # GET /appointments/1/edit
  def edit
  end

  # POST /appointments
  # POST /appointments.json
  def create
    @appointment = Appointment.new(appointment_params)

    respond_to do |format|
      if @appointment.save
        AppointmentMailer.with(appointment: @appointment).new_appointment_email.deliver_now
        format.html { redirect_to @appointment, notice: 'Appointment was successfully created.' }
        format.json { render :show, status: :created, location: @appointment }
      else
        format.html { render :new }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /appointments/1
  # PATCH/PUT /appointments/1.json
  def update
    respond_to do |format|
      if @appointment.update(appointment_params)
        format.html { redirect_to @appointment, notice: 'Appointment was successfully updated.' }
        format.json { render :show, status: :ok, location: @appointment }
      else
        format.html { render :edit }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /appointments/1
  # DELETE /appointments/1.json
  def destroy
    @appointment.destroy
    respond_to do |format|
      format.html { redirect_to appointments_url, notice: 'Appointment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def update_status
    if @appointment.present?
      @appointment.update(status: true)
      AppointmentMailer.with(appointment: @appointment).appointment_reply_email.deliver_now
      redirect_to root_path
    else
      redirect_to root_path
    end
  end

  def send_prescription
    @note = Note.new
  end

  def save_prescription
    @note = Note.new(note_params)
    @note.save
    AppointmentMailer.with(note: @note).send_prescription_email.deliver_now
    redirect_to root_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_appointment
      if params[:appointment_id]
        @appointment = Appointment.find(params[:appointment_id])
      else
        @appointment = Appointment.find(params[:id])
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def appointment_params
      params.require(:appointment).permit(:description, :start_time, :end_time, :doctor_id, :patient_id)
    end

    def note_params
      params.require(:note).permit(:description, :appointment_id, :doctor_id, :patient_id)
    end
end

app/controllers/doctors/registrations_controller.rb
# frozen_string_literal: true

class Doctors::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  def create
    if params[:user][:type] == "Doctor"
      @doctor = Doctor.new(configure_sign_up_params)
       @doctor.save 
      sign_in(@doctor, scope: :doctor)
      redirect_to root_path
    else
      configure_sign_up_params.extract!(:specialist)
      @patient = Patient.new(configure_sign_up_params)
      @patient.save
      sign_in(@patient, scope: :patient)
      redirect_to root_path
    end
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

   protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    if params[:type] == "Doctor"
      params.require(:doctor).permit(:first_name, :email, :last_name, :specialist, :password, :password_confirmation)
    else
      params.require(:doctor).permit(:first_name, :email, :last_name, :password, :password_confirmation)
    end
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/doctors/sessions_controller.rb
# frozen_string_literal: true

class Doctors::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  def new
    super
  end

  # POST /resource/sign_in
  def create
    if params[:user][:type] == "Patient"
      @patient = Patient.find_by_email(params[:doctor][:email])
      if @patient.present?
        sign_in(@patient, scope: :patient)
        redirect_to root_path
      else
        @doctor = Doctor.new
        render :new
      end
    else
      super
    end
  end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	if current_doctor
  		redirect_to appointments_path
  	else
  		@doctors = Doctor.all
  	end

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def set_link
		"hello"
	end
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/appointments/_form.html.erb
<%= form_with(model: appointment, local: true) do |form| %>
  <% if appointment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(appointment.errors.count, "error") %> prohibited this appointment from being saved:</h2>

      <ul>
      <% appointment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :start_time %>
    <%= form.text_field :start_time %>
  </div>

  <div class="field">
    <%= form.label :end_time %>
    <%= form.text_field :end_time %>
    <%= form.hidden_field :doctor_id, value: @doctor.id %>
    <%= form.hidden_field :patient_id, value: current_patient.id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

<script type="text/javascript">
  
  $(document).ready(function () {
    $("#appointment_start_time" ).datetimepicker({
          dateFormat: 'yy-mm-dd',
          timeFormat: 'HH:mm:ss',
          step: 30,
          onShow: function () {
              this.setOptions({
                  maxDate:$('#appointment_end_time').val()?$('#appointment_end_time').val():false,
                 // maxTime:$('#appointment_end_time').val()?$('#appointment_end_time').val():false
              });
          }
    }).attr('readonly', 'readonly');
    $( "#appointment_end_time" ).datetimepicker({
        dateFormat: 'yy-mm-dd',
        timeFormat: 'HH:mm:ss',
        step: 30,
          onShow: function () {
              this.setOptions({
                  minDate:$('#appointment_start_time').val()?$('#appointment_start_time').val():false,
                 // minTime:$('#appointment_start_time').val()?$('#appointment_start_time').val():false
              });
          }                    
    }).attr('readonly', 'readonly'); 
  });
</script>

app/views/appointments/edit.html.erb
<h1>Editing Appointment</h1>

<%= render 'form', appointment: @appointment %>

<%= link_to 'Show', @appointment %> |
<%= link_to 'Back', appointments_path %>

app/views/appointments/index.html.erb
<h1>Appointments</h1>
<div><%= link_to "Today's Appointments", appointments_path(type: "today") %></div>

<table class="ui selectable celled striped table padded">
  <thead>
    <tr>
      <th class="center aligned">Patient Name</th>
      <th class="center aligned">Description</th>
      <th class="center aligned">Start time</th>
      <th class="center aligned">End time</th>
      
      <th class="center aligned" ></th>
    </tr>
  </thead>

  <tbody>
    <% @appointments.each do |appointment| %>
      <tr>
        <td><%= appointment.patient.full_name %></td>
        <td><%= appointment.description %></td>
        <td><%= appointment.start_time.strftime("%Y-%m-%d %H:%M %p") %></td>
        <td><%= appointment.end_time.strftime("%Y-%m-%d %H:%M %p") %></td>
        <td>
          <% if Time.now > appointment.end_time %>
            <%= link_to 'Send Prescription', appointment_send_prescription_path(appointment.id) %>
          <% end %>
        </td>
        <td><%= link_to 'Destroy', appointment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/appointments/new.html.erb
<h1>New Appointment</h1>

<%= render 'form', appointment: @appointment %>

<%= link_to 'Back', appointments_path %>

app/views/appointments/send_prescription.html.erb
<%= tinymce_assets %>
<%= form_with(model: @note, url: save_prescription_appointments_path) do |form| %>
  <% if @note.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@note.errors.count, "error") %> prohibited this prescription from being saved:</h2>

      <ul>
      <% @note.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, :class => "tinymce", :rows => 10, :cols => 40 %>
    <%= form.hidden_field :appointment_id, value: @appointment.id %>
    <%= form.hidden_field :doctor_id, value: current_doctor.id %>
    <%= form.hidden_field :patient_id, value: @appointment.patient.id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>
<%= tinymce %>

app/views/appointments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @appointment.description %>
</p>

<p>
  <strong>Start time:</strong>
  <%= @appointment.start_time %>
</p>

<p>
  <strong>End time:</strong>
  <%= @appointment.end_time %>
</p>

<p>
  <strong>Doctor:</strong>
  <%= @appointment.doctor_id %>
</p>

<p>
  <strong>Patient:</strong>
  <%= @appointment.patient_id %>
</p>

<%= link_to 'Edit', edit_appointment_path(@appointment) %> |
<%= link_to 'Back', appointments_path %>

app/views/home/index.html.erb
<h1>Doctors</h1>
<table class="ui selectable celled striped table padded">
  <thead>
    <th class="center aligned">Doctor Name</th>
    <th class="center aligned">Speciality</th>
    <th class="center aligned">Email</th>
    <th class="center aligned">Appointment</th>
  </thead>
  <tbody>
    <% @doctors.each do |doctor| %>
      <tr>
        <td><%= doctor.full_name %></td>
        <td><%= doctor.specialist %></td>
        <td><%= doctor.email %></td>
        <td><%= link_to 'Add Appointment', new_appointment_path(id: doctor.id), class:"ui button red inverted" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Doctor-Appointment" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%#= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%#= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%#= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%#= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%#= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" ,"data-turbolinks-track" => true %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">Doctor-Appointment</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <% if current_doctor %>
              <li><%= link_to('Logout', destroy_doctor_session_path, method: :delete) %></li>
            <% elsif current_patient %>
              <li><%= link_to('Logout', destroy_patient_session_path, method: :delete) %></li>
            <% else %>
              <li><%= link_to('login', login_path) %></li>
              <li><%= link_to('signup', signup_path) %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        <!-- <div class="col-lg-3">
          <div class="well sidebar-nav">
            <h3>Sidebar</h3>
            <ul class="nav nav-list">
              <li class="nav-header">Sidebar</li>
              
            </ul>
          </div><!--/.well -->
        <!-- </div> -->
        <!--/span-->
      </div><!--/row-->
   
      <!-- <footer>
        <p>&copy; Company 2019</p>
      </footer> -->

    </div> <!-- /container -->

  </body>
</html>